In [1]:
#importacion de las librerias
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("tourism_dataset_5000.csv")

In [3]:
df

,Tourist ID,Age,Interests,Preferred Tour Duration,Accessibility,Site Name,Sites Visited,Tour Duration,Route ID,Tourist Rating,System Response Time,Recommendation Accuracy,VR Experience Quality,Satisfaction
0,1,48,"['Architecture', 'Art', 'History']",5,False,Eiffel Tower,"['Eiffel Tower', 'Great Wall of China', 'Taj M...",7,1000,1.6,3.73,97,4.5,3
1,2,37,"['Cultural', 'Nature']",6,False,Colosseum,['Great Wall of China'],1,2000,2.6,2.89,90,4.5,3
2,3,43,"['History', 'Art', 'Architecture']",6,True,Machu Picchu,['Eiffel Tower'],2,3000,1.7,2.22,94,4.7,3
3,4,46,"['Cultural', 'Art', 'Architecture']",8,False,Colosseum,"['Machu Picchu', 'Taj Mahal']",5,4000,2.0,2.34,92,4.7,3
4,5,53,"['Architecture', 'Art']",5,True,Colosseum,"['Machu Picchu', 'Taj Mahal', 'Great Wall of C...",7,5000,3.7,2.00,96,4.8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,31,"['Architecture', 'History', 'Cultural']",3,False,Great Wall of China,['Great Wall of China'],2,4996000,3.9,2.53,100,4.4,4
4996,4997,28,"['Architecture', 'Cultural', 'Nature']",7,True,Great Wall of China,['Colosseum'],1,4997000,4.3,1.53,100,5.0,4
4997,4998,42,"['History', 'Cultural', 'Nature']",3,True,Machu Picchu,['Taj Mahal'],1,4998000,3.2,3.99,89,4.4,3
4998,4999,58,"['Cultural', 'Art', 'History']",5,False,Colosseum,"['Taj Mahal', 'Great Wall of China', 'Colosseum']",7,4999000,2.5,2.13,98,4.4,3
4999,5000,32,['Nature'],4,False,Colosseum,['Great Wall of China'],1,5000000,1.9,2.99,92,4.8,3